using CoreBusiness.Dropdown;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Plugins.DataStore.InMemory.Dropdown
{
    public class JournalInMemoryRepository : IJournalRepository
    {
        private readonly List<Journal> _journalName;
        public JournalInMemoryRepository()
        {
            _journalName = new List<Journal>()
            {
                new Journal {Name = "Frontiers", JournalId = "FALGY" }, new Journal {Name = "Frontiers", JournalId = "FANES" }, new Journal {Name = "Frontiers", JournalId = "FCVM" },
                new Journal {Name = "Frontiers", JournalId = "FDGTH" }, new Journal {Name = "Frontiers", JournalId = "FDMED" }, new Journal {Name = "Frontiers", JournalId = "FENVH" },
                new Journal {Name = "Frontiers", JournalId = "FEPID" }, new Journal {Name = "Frontiers", JournalId = "FGWH" }, new Journal {Name = "Frontiers", JournalId = "FLUPU" },
                new Journal {Name = "Frontiers", JournalId = "FMEDT" }, new Journal {Name = "Frontiers", JournalId = "FNUME" }, new Journal {Name = "Frontiers", JournalId = "FPAIN" },
                new Journal {Name = "Frontiers", JournalId = "FPED" }, new Journal {Name = "Frontiers", JournalId = "FRADI" }, new Journal {Name = "Frontiers", JournalId = "FRCHA" },
                new Journal {Name = "Frontiers", JournalId = "FRESC" }, new Journal {Name = "Frontiers", JournalId = "FRHS" }, new Journal {Name = "Frontiers", JournalId = "FROH" },
                new Journal {Name = "Frontiers", JournalId = "FRPH" }, new Journal {Name = "Frontiers", JournalId = "FRTRA" }, new Journal {Name = "Frontiers", JournalId = "FSPOR" },
                new Journal {Name = "Frontiers", JournalId = "FSURG " }, 
                
                new Journal {Name = "T&F", JournalId = "CAFS" }, new Journal {Name = "T&F", JournalId = "CAGE" }, new Journal {Name = "T&F", JournalId = "CAIC" }, 
                new Journal {Name = "T&F", JournalId = "CAJI" }, new Journal {Name = "T&F", JournalId = "CAJL" }, new Journal {Name = "T&F", JournalId = "CAJP" }, 
                new Journal {Name = "T&F", JournalId = "CALM" }, new Journal {Name = "T&F", JournalId = "CALR" }, new Journal {Name = "T&F", JournalId = "CAME" }, 
                new Journal {Name = "T&F", JournalId = "CANF" }, new Journal {Name = "T&F", JournalId = "CANG" }, new Journal {Name = "T&F", JournalId = "CAPR" }, 
                new Journal {Name = "T&F", JournalId = "CAST" }, new Journal {Name = "T&F", JournalId = "CAVP" }, new Journal {Name = "T&F", JournalId = "CBHS" }, 
                new Journal {Name = "T&F", JournalId = "CBIE" }, new Journal {Name = "T&F", JournalId = "CBJG" }, new Journal {Name = "T&F", JournalId = "CBST" },
                new Journal {Name = "T&F", JournalId = "CCAS" }, new Journal {Name = "T&F", JournalId = "CCCP" }, new Journal {Name = "T&F", JournalId = "CCED" },
                new Journal {Name = "T&F", JournalId = "CCHG" }, new Journal {Name = "T&F", JournalId = "CCIT" }, new Journal {Name = "T&F", JournalId = "CCLA" },
                new Journal {Name = "T&F", JournalId = "CCOS" }, new Journal {Name = "T&F", JournalId = "CCPO" }, new Journal {Name = "T&F", JournalId = "CCSA" },
                new Journal {Name = "T&F", JournalId = "CCUT" }, new Journal {Name = "T&F", JournalId = "CCWF" }, new Journal {Name = "T&F", JournalId = "CDAN" },
                new Journal {Name = "T&F", JournalId = "CDIP" }, new Journal {Name = "T&F", JournalId = "CDIS" }, new Journal {Name = "T&F", JournalId = "CDSA" },
                new Journal {Name = "T&F", JournalId = "CEDE" }, new Journal {Name = "T&F", JournalId = "CEEE" }, new Journal {Name = "T&F", JournalId = "CEPS" },
                new Journal {Name = "T&F", JournalId = "CERA" }, new Journal {Name = "T&F", JournalId = "CESR" }, new Journal {Name = "T&F", JournalId = "CESW" },
                new Journal {Name = "T&F", JournalId = "CETH" }, new Journal {Name = "T&F", JournalId = "CFAI" }, new Journal {Name = "T&F", JournalId = "CGDE" },
                new Journal {Name = "T&F", JournalId = "CGEE" }, new Journal {Name = "T&F", JournalId = "CGSE" }, new Journal {Name = "T&F", JournalId = "CGSJ" },
                new Journal {Name = "T&F", JournalId = "CHER" }, new Journal {Name = "T&F", JournalId = "CICM" }, new Journal {Name = "T&F", JournalId = "CICT" },
                new Journal {Name = "T&F", JournalId = "CIEJ" }, new Journal {Name = "T&F", JournalId = "CIEY" }, new Journal {Name = "T&F", JournalId = "CIJL" },
                new Journal {Name = "T&F", JournalId = "CIMW" }, new Journal {Name = "T&F", JournalId = "CIPS" }, new Journal {Name = "T&F", JournalId = "CIRL" },
                new Journal {Name = "T&F", JournalId = "CIRS" }, new Journal {Name = "T&F", JournalId = "CISP" }, new Journal {Name = "T&F", JournalId = "CIST" },
                new Journal {Name = "T&F", JournalId = "CJAC" }, new Journal {Name = "T&F", JournalId = "CJAS" }, new Journal {Name = "T&F", JournalId = "CJCA" },
                new Journal {Name = "T&F", JournalId = "CJCP" }, new Journal {Name = "T&F", JournalId = "CJEH" }, new Journal {Name = "T&F", JournalId = "CJEM" },
                new Journal {Name = "T&F", JournalId = "CJEN" }, new Journal {Name = "T&F", JournalId = "CJGR" }, new Journal {Name = "T&F", JournalId = "CJHD" },
                new Journal {Name = "T&F", JournalId = "CJID" }, new Journal {Name = "T&F", JournalId = "CJIS" }, new Journal {Name = "T&F", JournalId = "CJMM" },
                new Journal {Name = "T&F", JournalId = "CJMS" }, new Journal {Name = "T&F", JournalId = "CJOE" }, new Journal {Name = "T&F", JournalId = "CJOL" },
                new Journal {Name = "T&F", JournalId = "CJPH" }, new Journal {Name = "T&F", JournalId = "CJSC" }, new Journal {Name = "T&F", JournalId = "CJUT" },
                new Journal {Name = "T&F", JournalId = "CJWR" }, new Journal {Name = "T&F", JournalId = "CJYS" }, new Journal {Name = "T&F", JournalId = "CLOE" },
                new Journal {Name = "T&F", JournalId = "CMEH" }, new Journal {Name = "T&F", JournalId = "CMHR" }, new Journal {Name = "T&F", JournalId = "CMJS" },
                new Journal {Name = "T&F", JournalId = "CMUE" }, new Journal {Name = "T&F", JournalId = "CNAP" }, new Journal {Name = "T&F", JournalId = "CNGS" },
                new Journal {Name = "T&F", JournalId = "CNID" }, new Journal {Name = "T&F", JournalId = "CNPE" }, new Journal {Name = "T&F", JournalId = "CPAR" },
                new Journal {Name = "T&F", JournalId = "CPCS" }, new Journal {Name = "T&F", JournalId = "CPES" }, new Journal {Name = "T&F", JournalId = "CPOS" },
                new Journal {Name = "T&F", JournalId = "CPSA" }, new Journal {Name = "T&F", JournalId = "CRDE" }, new Journal {Name = "T&F", JournalId = "CREA" },
                new Journal {Name = "T&F", JournalId = "CRES" }, new Journal {Name = "T&F", JournalId = "CRHE" }, new Journal {Name = "T&F", JournalId = "CRPE" },
                new Journal {Name = "T&F", JournalId = "CSAC" }, new Journal {Name = "T&F", JournalId = "CSAD" }, new Journal {Name = "T&F", JournalId = "CSCE" },
                new Journal {Name = "T&F", JournalId = "CSES" }, new Journal {Name = "T&F", JournalId = "CSHE" }, new Journal {Name = "T&F", JournalId = "CSID" },
                new Journal {Name = "T&F", JournalId = "CSJE" }, new Journal {Name = "T&F", JournalId = "CSLM" }, new Journal {Name = "T&F", JournalId = "CSOS" },
                new Journal {Name = "T&F", JournalId = "CSPP" }, new Journal {Name = "T&F", JournalId = "CSWA" }, new Journal {Name = "T&F", JournalId = "CTAS" },
                new Journal {Name = "T&F", JournalId = "CTHE" }, new Journal {Name = "T&F", JournalId = "CTQM" }, new Journal {Name = "T&F", JournalId = "CTTE" },
                new Journal {Name = "T&F", JournalId = "CWSE" }, new Journal {Name = "T&F", JournalId = "FANC" }, new Journal {Name = "T&F", JournalId = "FBEP" },
                new Journal {Name = "T&F", JournalId = "FCCP" }, new Journal {Name = "T&F", JournalId = "FCSP" }, new Journal {Name = "T&F", JournalId = "FDEM" },
                new Journal {Name = "T&F", JournalId = "FEEJ" }, new Journal {Name = "T&F", JournalId = "FEUS" }, new Journal {Name = "T&F", JournalId = "FGRP" },
                new Journal {Name = "T&F", JournalId = "FICH" }, new Journal {Name = "T&F", JournalId = "FINP" }, new Journal {Name = "T&F", JournalId = "FIPS" },
                new Journal {Name = "T&F", JournalId = "FJCS" }, new Journal {Name = "T&F", JournalId = "FJHR" }, new Journal {Name = "T&F", JournalId = "FJLS" },
                new Journal {Name = "T&F", JournalId = "FJPS" }, new Journal {Name = "T&F", JournalId = "FLGH" }, new Journal {Name = "T&F", JournalId = "FNAS" },
                new Journal {Name = "T&F", JournalId = "FRFS" }, new Journal {Name = "T&F", JournalId = "FRVR" }, new Journal {Name = "T&F", JournalId = "FSIJ" },
                new Journal {Name = "T&F", JournalId = "FSLA" }, new Journal {Name = "T&F", JournalId = "FTMP" }, new Journal {Name = "T&F", JournalId = "FTUR" },
                new Journal {Name = "T&F", JournalId = "GASC" }, new Journal {Name = "T&F", JournalId = "GCEE" }, new Journal {Name = "T&F", JournalId = "GCHE" },
                new Journal {Name = "T&F", JournalId = "GCMC" }, new Journal {Name = "T&F", JournalId = "GCMR" }, new Journal {Name = "T&F", JournalId = "GCOM" },
                new Journal {Name = "T&F", JournalId = "GCRY" }, new Journal {Name = "T&F", JournalId = "GECD" }, new Journal {Name = "T&F", JournalId = "GEIN" },
                new Journal {Name = "T&F", JournalId = "GENO" }, new Journal {Name = "T&F", JournalId = "GERR" }, new Journal {Name = "T&F", JournalId = "GHAN" },
                new Journal {Name = "T&F", JournalId = "GHPR" }, new Journal {Name = "T&F", JournalId = "GIEH" }, new Journal {Name = "T&F", JournalId = "GITR" },
                new Journal {Name = "T&F", JournalId = "GNCC" }, new Journal {Name = "T&F", JournalId = "GNST" }, new Journal {Name = "T&F", JournalId = "GOMS" },
                new Journal {Name = "T&F", JournalId = "GPAS" }, new Journal {Name = "T&F", JournalId = "GPCL" }, new Journal {Name = "T&F", JournalId = "GRAD" },
                new Journal {Name = "T&F", JournalId = "GSCO" }, new Journal {Name = "T&F", JournalId = "GSCS" }, new Journal {Name = "T&F", JournalId = "GSOL" },
                new Journal {Name = "T&F", JournalId = "GSRP" }, new Journal {Name = "T&F", JournalId = "GSTA" }, new Journal {Name = "T&F", JournalId = "GTPT" },
                new Journal {Name = "T&F", JournalId = "GVIR" }, new Journal {Name = "T&F", JournalId = "NDCR" }, new Journal {Name = "T&F", JournalId = "NERE" },
                new Journal {Name = "T&F", JournalId = "NEST" }, new Journal {Name = "T&F", JournalId = "NGRK" }, new Journal {Name = "T&F", JournalId = "NILE" },
                new Journal {Name = "T&F", JournalId = "NVPP" }, new Journal {Name = "T&F", JournalId = "NVSD" }, new Journal {Name = "T&F", JournalId = "PCEM" },
                new Journal {Name = "T&F", JournalId = "PCGN" }, new Journal {Name = "T&F", JournalId = "PCNP" }, new Journal {Name = "T&F", JournalId = "PECP" },
                new Journal {Name = "T&F", JournalId = "PLAT" }, new Journal {Name = "T&F", JournalId = "PLCP" }, new Journal {Name = "T&F", JournalId = "PMEM" },
                new Journal {Name = "T&F", JournalId = "PNRH" }, new Journal {Name = "T&F", JournalId = "PQJE" }, new Journal {Name = "T&F", JournalId = "PVIS" },
                new Journal {Name = "T&F", JournalId = "PWSR" }, new Journal {Name = "T&F", JournalId = "RAAF" }, new Journal {Name = "T&F", JournalId = "RAAR" },
                new Journal {Name = "T&F", JournalId = "RABD" }, new Journal {Name = "T&F", JournalId = "RABF" }, new Journal {Name = "T&F", JournalId = "RABR" },
                new Journal {Name = "T&F", JournalId = "RACO" }, new Journal {Name = "T&F", JournalId = "RACR" }, new Journal {Name = "T&F", JournalId = "RAED" },
                new Journal {Name = "T&F", JournalId = "RAEE" }, new Journal {Name = "T&F", JournalId = "RAER" }, new Journal {Name = "T&F", JournalId = "RAFR" },
                new Journal {Name = "T&F", JournalId = "RAGE" }, new Journal {Name = "T&F", JournalId = "RAGN" }, new Journal {Name = "T&F", JournalId = "RAGR" },
                new Journal {Name = "T&F", JournalId = "RAHR" }, new Journal {Name = "T&F", JournalId = "RAHS" }, new Journal {Name = "T&F", JournalId = "RAIE" },
                new Journal {Name = "T&F", JournalId = "RAJC" }, new Journal {Name = "T&F", JournalId = "RAJM" }, new Journal {Name = "T&F", JournalId = "RAJS" },
                new Journal {Name = "T&F", JournalId = "RAJT" }, new Journal {Name = "T&F", JournalId = "RAJW" }, new Journal {Name = "T&F", JournalId = "RALL" },
                new Journal {Name = "T&F", JournalId = "RAMA" }, new Journal {Name = "T&F", JournalId = "RAMH" }, new Journal {Name = "T&F", JournalId = "RAMO" },
                new Journal {Name = "T&F", JournalId = "RANZ" }, new Journal {Name = "T&F", JournalId = "RAPL" }, new Journal {Name = "T&F", JournalId = "RAPS" },
                new Journal {Name = "T&F", JournalId = "RAPT" }, new Journal {Name = "T&F", JournalId = "RARS" }, new Journal {Name = "T&F", JournalId = "RART" },
                new Journal {Name = "T&F", JournalId = "RASA" }, new Journal {Name = "T&F", JournalId = "RASI" }, new Journal {Name = "T&F", JournalId = "RASP" },
                new Journal {Name = "T&F", JournalId = "RASR" }, new Journal {Name = "T&F", JournalId = "RASW" }, new Journal {Name = "T&F", JournalId = "RAZA" },
                new Journal {Name = "T&F", JournalId = "RBEB" }, new Journal {Name = "T&F", JournalId = "RBEC" }, new Journal {Name = "T&F", JournalId = "RBER" },
                new Journal {Name = "T&F", JournalId = "RBJH" }, new Journal {Name = "T&F", JournalId = "RBRI" }, new Journal {Name = "T&F", JournalId = "RBSP" },
                new Journal {Name = "T&F", JournalId = "RCAA" }, new Journal {Name = "T&F", JournalId = "RCAD" }, new Journal {Name = "T&F", JournalId = "RCAF" },
                new Journal {Name = "T&F", JournalId = "RCAP" }, new Journal {Name = "T&F", JournalId = "RCAU" }, new Journal {Name = "T&F", JournalId = "RCBQ" },
                new Journal {Name = "T&F", JournalId = "RCCC" }, new Journal {Name = "T&F", JournalId = "RCCM" }, new Journal {Name = "T&F", JournalId = "RCDS" },
                new Journal {Name = "T&F", JournalId = "RCED" }, new Journal {Name = "T&F", JournalId = "RCFP" }, new Journal {Name = "T&F", JournalId = "RCIS" },
                new Journal {Name = "T&F", JournalId = "RCIT" }, new Journal {Name = "T&F", JournalId = "RCJD" }, new Journal {Name = "T&F", JournalId = "RCLH" },
                new Journal {Name = "T&F", JournalId = "RCLP" }, new Journal {Name = "T&F", JournalId = "RCLS" }, new Journal {Name = "T&F", JournalId = "RCMH" },
                new Journal {Name = "T&F", JournalId = "RCMM" }, new Journal {Name = "T&F", JournalId = "RCMT" }, new Journal {Name = "T&F", JournalId = "RCNJ" },
                new Journal {Name = "T&F", JournalId = "RCNS" }, new Journal {Name = "T&F", JournalId = "RCOA" }, new Journal {Name = "T&F", JournalId = "RCON" },
                new Journal {Name = "T&F", JournalId = "RCRA" }, new Journal {Name = "T&F", JournalId = "RCRC" }, new Journal {Name = "T&F", JournalId = "RCRE" },
                new Journal {Name = "T&F", JournalId = "RCRI" }, new Journal {Name = "T&F", JournalId = "RCSA" }, new Journal {Name = "T&F", JournalId = "RCSM" },
                new Journal {Name = "T&F", JournalId = "RCSO" }, new Journal {Name = "T&F", JournalId = "RCTC" }, new Journal {Name = "T&F", JournalId = "RCUS" },
                new Journal {Name = "T&F", JournalId = "RCWR" }, new Journal {Name = "T&F", JournalId = "RCYB" }, new Journal {Name = "T&F", JournalId = "RDAP" },
                new Journal {Name = "T&F", JournalId = "RDES" }, new Journal {Name = "T&F", JournalId = "RDIS" }, new Journal {Name = "T&F", JournalId = "RDSP" },
                new Journal {Name = "T&F", JournalId = "RDSR" }, new Journal {Name = "T&F", JournalId = "RDST" }, new Journal {Name = "T&F", JournalId = "REAE" },
                new Journal {Name = "T&F", JournalId = "REAJ" }, new Journal {Name = "T&F", JournalId = "REAL" }, new Journal {Name = "T&F", JournalId = "REAR" },
                new Journal {Name = "T&F", JournalId = "REAT" }, new Journal {Name = "T&F", JournalId = "RECJ" }, new Journal {Name = "T&F", JournalId = "RECO" },
                new Journal {Name = "T&F", JournalId = "RECP" }, new Journal {Name = "T&F", JournalId = "RECQ" }, new Journal {Name = "T&F", JournalId = "RECR" },
                new Journal {Name = "T&F", JournalId = "REHD" }, new Journal {Name = "T&F", JournalId = "REHE" }, new Journal {Name = "T&F", JournalId = "REIA" },
                new Journal {Name = "T&F", JournalId = "REJF" }, new Journal {Name = "T&F", JournalId = "REMF" }, new Journal {Name = "T&F", JournalId = "RENC" },
                new Journal {Name = "T&F", JournalId = "RENO" }, new Journal {Name = "T&F", JournalId = "RERS" }, new Journal {Name = "T&F", JournalId = "RESM" },
                new Journal {Name = "T&F", JournalId = "RESO" }, new Journal {Name = "T&F", JournalId = "RESW" }, new Journal {Name = "T&F", JournalId = "RETN" },
                new Journal {Name = "T&F", JournalId = "RETT" }, new Journal {Name = "T&F", JournalId = "REUS" }, new Journal {Name = "T&F", JournalId = "RFAN" },
                new Journal {Name = "T&F", JournalId = "RFEC" }, new Journal {Name = "T&F", JournalId = "RFEM" }, new Journal {Name = "T&F", JournalId = "RFIA" },
                new Journal {Name = "T&F", JournalId = "RFJP" }, new Journal {Name = "T&F", JournalId = "RFTG" }, new Journal {Name = "T&F", JournalId = "RGAF" },
                new Journal {Name = "T&F", JournalId = "RGBE" }, new Journal {Name = "T&F", JournalId = "RGER" }, new Journal {Name = "T&F", JournalId = "RGIH" },
                new Journal {Name = "T&F", JournalId = "RGLO" }, new Journal {Name = "T&F", JournalId = "RGPH" }, new Journal {Name = "T&F", JournalId = "RHEI" },
                new Journal {Name = "T&F", JournalId = "RHOS" }, new Journal {Name = "T&F", JournalId = "RHPB" }, new Journal {Name = "T&F", JournalId = "RHPR" },
                new Journal {Name = "T&F", JournalId = "RHRC" }, new Journal {Name = "T&F", JournalId = "RHSR" }, new Journal {Name = "T&F", JournalId = "RIAC" },
                new Journal {Name = "T&F", JournalId = "RIAD" }, new Journal {Name = "T&F", JournalId = "RIAJ" }, new Journal {Name = "T&F", JournalId = "RIBS" },
                new Journal {Name = "T&F", JournalId = "RICE" }, new Journal {Name = "T&F", JournalId = "RICO" }, new Journal {Name = "T&F", JournalId = "RICS" },
                new Journal {Name = "T&F", JournalId = "RICT" }, new Journal {Name = "T&F", JournalId = "RIEJ" },new Journal {Name = "T&F", JournalId = "RIES" },
                new Journal {Name = "T&F", JournalId = "RIFA" }, new Journal {Name = "T&F", JournalId = "RIHR" }, new Journal {Name = "T&F", JournalId = "RIIJ" },
                new Journal {Name = "T&F", JournalId = "RIJJ" }, new Journal {Name = "T&F", JournalId = "RIJP" }, new Journal {Name = "T&F", JournalId = "RIJS" },
                new Journal {Name = "T&F", JournalId = "RILL" }, new Journal {Name = "T&F", JournalId = "RIOB" }, new Journal {Name = "T&F", JournalId = "RIOR" },
                new Journal {Name = "T&F", JournalId = "RIPJ" }, new Journal {Name = "T&F", JournalId = "RIRS" }, new Journal {Name = "T&F", JournalId = "RIRT" },
                new Journal {Name = "T&F", JournalId = "RISB" }, new Journal {Name = "T&F", JournalId = "RJAB" }, new Journal {Name = "T&F", JournalId = "RJAC" },
                new Journal {Name = "T&F", JournalId = "RJAL" }, new Journal {Name = "T&F", JournalId = "RJAR" }, new Journal {Name = "T&F", JournalId = "RJAS" },
                new Journal {Name = "T&F", JournalId = "RJAU" }, new Journal {Name = "T&F", JournalId = "RJAV" }, new Journal {Name = "T&F", JournalId = "RJAZ" },
                new Journal {Name = "T&F", JournalId = "RJBS" }, new Journal {Name = "T&F", JournalId = "RJCE" }, new Journal {Name = "T&F", JournalId = "RJCG" },
                new Journal {Name = "T&F", JournalId = "RJCM" }, new Journal {Name = "T&F", JournalId = "RJCS" }, new Journal {Name = "T&F", JournalId = "RJDR" },
                new Journal {Name = "T&F", JournalId = "RJEA" }, new Journal {Name = "T&F", JournalId = "RJEQ" }, new Journal {Name = "T&F", JournalId = "RJFS" },
                new Journal {Name = "T&F", JournalId = "RJGE" }, new Journal {Name = "T&F", JournalId = "RJHT" }, new Journal {Name = "T&F", JournalId = "RJII" },
                new Journal {Name = "T&F", JournalId = "RJKC" }, new Journal {Name = "T&F", JournalId = "RJLA" }, new Journal {Name = "T&F", JournalId = "RJLS" },
                new Journal {Name = "T&F", JournalId = "RJME" }, new Journal {Name = "T&F", JournalId = "RJML" }, new Journal {Name = "T&F", JournalId = "RJMP" },
                new Journal {Name = "T&F", JournalId = "RJOP" }, new Journal {Name = "T&F", JournalId = "RJOS" }, new Journal {Name = "T&F", JournalId = "RJPN" },
                new Journal {Name = "T&F", JournalId = "RJPP" }, new Journal {Name = "T&F", JournalId = "RJTH" }, new Journal {Name = "T&F", JournalId = "RJTO" },
                new Journal {Name = "T&F", JournalId = "RJTR" }, new Journal {Name = "T&F", JournalId = "RJTS" }, new Journal {Name = "T&F", JournalId = "RJUF" },
                new Journal {Name = "T&F", JournalId = "RJUS" }, new Journal {Name = "T&F", JournalId = "RJVP" }, new Journal {Name = "T&F", JournalId = "RKLJ" },
                new Journal {Name = "T&F", JournalId = "RLAH" }, new Journal {Name = "T&F", JournalId = "RLAW" }, new Journal {Name = "T&F", JournalId = "RLCC" },
                new Journal {Name = "T&F", JournalId = "RLET" }, new Journal {Name = "T&F", JournalId = "RLFM" }, new Journal {Name = "T&F", JournalId = "RLIT" },
                new Journal {Name = "T&F", JournalId = "RLLJ" }, new Journal {Name = "T&F", JournalId = "RLMS" }, new Journal {Name = "T&F", JournalId = "RLSH" },
                new Journal {Name = "T&F", JournalId = "RLWR" }, new Journal {Name = "T&F", JournalId = "RMAA" }, new Journal {Name = "T&F", JournalId = "RMAR" },
                new Journal {Name = "T&F", JournalId = "RMDJ" }, new Journal {Name = "T&F", JournalId = "RMED" }, new Journal {Name = "T&F", JournalId = "RMET" },
                new Journal {Name = "T&F", JournalId = "RMIR" }, new Journal {Name = "T&F", JournalId = "RMJM" }, new Journal {Name = "T&F", JournalId = "RMLE" },
                new Journal {Name = "T&F", JournalId = "RMLI" }, new Journal {Name = "T&F", JournalId = "RMMC" }, new Journal {Name = "T&F", JournalId = "RMMD" },
                new Journal {Name = "T&F", JournalId = "RMMM" }, new Journal {Name = "T&F", JournalId = "RMNW" }, new Journal {Name = "T&F", JournalId = "RMPS" },
                new Journal {Name = "T&F", JournalId = "RMRA" }, new Journal {Name = "T&F", JournalId = "RMSE" }, new Journal {Name = "T&F", JournalId = "RMUZ" },
                new Journal {Name = "T&F", JournalId = "RNAC" }, new Journal {Name = "T&F", JournalId = "RNHR" }, new Journal {Name = "T&F", JournalId = "RNMF" },
                new Journal {Name = "T&F", JournalId = "RNOR" }, new Journal {Name = "T&F", JournalId = "RNPA" }, new Journal {Name = "T&F", JournalId = "RNPR" },
                new Journal {Name = "T&F", JournalId = "RNRL" }, new Journal {Name = "T&F", JournalId = "ROCC" }, new Journal {Name = "T&F", JournalId = "ROUC" },
                new Journal {Name = "T&F", JournalId = "RPDM" }, new Journal {Name = "T&F", JournalId = "RPEP" }, new Journal {Name = "T&F", JournalId = "RPER" },
                new Journal {Name = "T&F", JournalId = "RPEX" }, new Journal {Name = "T&F", JournalId = "RPGI" }, new Journal {Name = "T&F", JournalId = "RPIA" },
                new Journal {Name = "T&F", JournalId = "RPIC" }, new Journal {Name = "T&F", JournalId = "RPIL" }, new Journal {Name = "T&F", JournalId = "RPLJ" },
                new Journal {Name = "T&F", JournalId = "RPMM" }, new Journal {Name = "T&F", JournalId = "RPOM" }, new Journal {Name = "T&F", JournalId = "RPOP" },
                new Journal {Name = "T&F", JournalId = "RPPA" }, new Journal {Name = "T&F", JournalId = "RPPE" }, new Journal {Name = "T&F", JournalId = "RPRN" },
                new Journal {Name = "T&F", JournalId = "RPRS" }, new Journal {Name = "T&F", JournalId = "RPRT" }, new Journal {Name = "T&F", JournalId = "RPSS" },
                new Journal {Name = "T&F", JournalId = "RPST" }, new Journal {Name = "T&F", JournalId = "RQFL" }, new Journal {Name = "T&F", JournalId = "RQJS" },
                new Journal {Name = "T&F", JournalId = "RRBB" }, new Journal {Name = "T&F", JournalId = "RREJ" }, new Journal {Name = "T&F", JournalId = "RREL" },
                new Journal {Name = "T&F", JournalId = "RREP" }, new Journal {Name = "T&F", JournalId = "RRER" }, new Journal {Name = "T&F", JournalId = "RREV" },
                new Journal {Name = "T&F", JournalId = "RRJC" }, new Journal {Name = "T&F", JournalId = "RRMA" }, new Journal {Name = "T&F", JournalId = "RRMC" },
                new Journal {Name = "T&F", JournalId = "RRME" }, new Journal {Name = "T&F", JournalId = "RRMX" }, new Journal {Name = "T&F", JournalId = "RROC" },
                new Journal {Name = "T&F", JournalId = "RRSO" }, new Journal {Name = "T&F", JournalId = "RSAD" }, new Journal {Name = "T&F", JournalId = "RSAH" },
                new Journal {Name = "T&F", JournalId = "RSAJ" }, new Journal {Name = "T&F", JournalId = "RSAR" }, new Journal {Name = "T&F", JournalId = "RSAU" },
                new Journal {Name = "T&F", JournalId = "RSCR" }, new Journal {Name = "T&F", JournalId = "RSDF" }, new Journal {Name = "T&F", JournalId = "RSEA" },
                new Journal {Name = "T&F", JournalId = "RSED" }, new Journal {Name = "T&F", JournalId = "RSEL" }, new Journal {Name = "T&F", JournalId = "RSER" },
                new Journal {Name = "T&F", JournalId = "RSET" }, new Journal {Name = "T&F", JournalId = "RSFO" }, new Journal {Name = "T&F", JournalId = "RSGJ" },
                new Journal {Name = "T&F", JournalId = "RSHJ" }, new Journal {Name = "T&F", JournalId = "RSHK" }, new Journal {Name = "T&F", JournalId = "RSIH" },
                new Journal {Name = "T&F", JournalId = "RSLT" }, new Journal {Name = "T&F", JournalId = "RSOC" }, new Journal {Name = "T&F", JournalId = "RSPH" },
                new Journal {Name = "T&F", JournalId = "RSSR" }, new Journal {Name = "T&F", JournalId = "RSTW" }, new Journal {Name = "T&F", JournalId = "RTAP" },
                new Journal {Name = "T&F", JournalId = "RTAS" }, new Journal {Name = "T&F", JournalId = "RTBS" }, new Journal {Name = "T&F", JournalId = "RTCC" },
                new Journal {Name = "T&F", JournalId = "RTEP" }, new Journal {Name = "T&F", JournalId = "RTHJ" }, new Journal {Name = "T&F", JournalId = "RTHP" },
                new Journal {Name = "T&F", JournalId = "RTLT" }, new Journal {Name = "T&F", JournalId = "RTPL" }, new Journal {Name = "T&F", JournalId = "RTPQ" },
                new Journal {Name = "T&F", JournalId = "RTPR" }, new Journal {Name = "T&F", JournalId = "RTRR" }, new Journal {Name = "T&F", JournalId = "RTRS" },
                new Journal {Name = "T&F", JournalId = "RUSI" }, new Journal {Name = "T&F", JournalId = "RVAT" }, new Journal {Name = "T&F", JournalId = "RWAP" },
                new Journal {Name = "T&F", JournalId = "RWAQ" }, new Journal {Name = "T&F", JournalId = "RWAS" }, new Journal {Name = "T&F", JournalId = "RWCR" },
                new Journal {Name = "T&F", JournalId = "RWHI" }, new Journal {Name = "T&F", JournalId = "RWHR" }, new Journal {Name = "T&F", JournalId = "RWLE" },
                new Journal {Name = "T&F", JournalId = "RWOR" }, new Journal {Name = "T&F", JournalId = "RWOW" }, new Journal {Name = "T&F", JournalId = "RWRD" },
                new Journal {Name = "T&F", JournalId = "SABO" }, new Journal {Name = "T&F", JournalId = "SAGA" }, new Journal {Name = "T&F", JournalId = "SAGB" },
                new Journal {Name = "T&F", JournalId = "SEHR" }, new Journal {Name = "T&F", JournalId = "SFDS" }, new Journal {Name = "T&F", JournalId = "SFOR" },
                new Journal {Name = "T&F", JournalId = "SGEO" }, new Journal {Name = "T&F", JournalId = "SJDR" }, new Journal {Name = "T&F", JournalId = "SJHT" },
                new Journal {Name = "T&F", JournalId = "SKON" }, new Journal {Name = "T&F", JournalId = "SMAR" }, new Journal {Name = "T&F", JournalId = "SMIL" },
                new Journal {Name = "T&F", JournalId = "SOSL" }, new Journal {Name = "T&F", JournalId = "SPSY" }, new Journal {Name = "T&F", JournalId = "SSLA" },
                new Journal {Name = "T&F", JournalId = "STHE" }, new Journal {Name = "T&F", JournalId = "SWOO" }, new Journal {Name = "T&F", JournalId = "TAAR" },
                new Journal {Name = "T&F", JournalId = "TAAS" }, new Journal {Name = "T&F", JournalId = "TACL" }, new Journal {Name = "T&F", JournalId = "TACS" },
                new Journal {Name = "T&F", JournalId = "TADL" }, new Journal {Name = "T&F", JournalId = "TADP" }, new Journal {Name = "T&F", JournalId = "TAEM" },
                new Journal {Name = "T&F", JournalId = "TAEN" }, new Journal {Name = "T&F", JournalId = "TAER" }, new Journal {Name = "T&F", JournalId = "TAFZ" },
                new Journal {Name = "T&F", JournalId = "TAGS" }, new Journal {Name = "T&F", JournalId = "TAMS" }, new Journal {Name = "T&F", JournalId = "TARC" },
                new Journal {Name = "T&F", JournalId = "TARF" }, new Journal {Name = "T&F", JournalId = "TARM" }, new Journal {Name = "T&F", JournalId = "TASC" },
                new Journal {Name = "T&F", JournalId = "TASR" }, new Journal {Name = "T&F", JournalId = "TATO" }, new Journal {Name = "T&F", JournalId = "TAVI" },
                new Journal {Name = "T&F", JournalId = "TBAP" }, new Journal {Name = "T&F", JournalId = "TBEM" }, new Journal {Name = "T&F", JournalId = "TBIS" },
                new Journal {Name = "T&F", JournalId = "TBIT" }, new Journal {Name = "T&F", JournalId = "TBPS" }, new Journal {Name = "T&F", JournalId = "TCAD" },
                new Journal {Name = "T&F", JournalId = "TCEM" }, new Journal {Name = "T&F", JournalId = "TCER" }, new Journal {Name = "T&F", JournalId = "TCFM" },
                new Journal {Name = "T&F", JournalId = "TCIS" }, new Journal {Name = "T&F", JournalId = "TCLD" }, new Journal {Name = "T&F", JournalId = "TCME" },
                new Journal {Name = "T&F", JournalId = "TCOM" }, new Journal {Name = "T&F", JournalId = "TCPO" }, new Journal {Name = "T&F", JournalId = "TDIA" },
                new Journal {Name = "T&F", JournalId = "TDMC" }, new Journal {Name = "T&F", JournalId = "TDSG" }, new Journal {Name = "T&F", JournalId = "TEAF" },
                new Journal {Name = "T&F", JournalId = "TEEL" }, new Journal {Name = "T&F", JournalId = "TEJS" }, new Journal {Name = "T&F", JournalId = "TENH" },
                new Journal {Name = "T&F", JournalId = "TENT" }, new Journal {Name = "T&F", JournalId = "TEOP" }, new Journal {Name = "T&F", JournalId = "TEPO" },
                new Journal {Name = "T&F", JournalId = "TESN" }, new Journal {Name = "T&F", JournalId = "TEST" }, new Journal {Name = "T&F", JournalId = "TETR" },
                new Journal {Name = "T&F", JournalId = "TFDT" }, new Journal {Name = "T&F", JournalId = "TFLS" }, new Journal {Name = "T&F", JournalId = "TGAC" },
                new Journal {Name = "T&F", JournalId = "TGCL" }, new Journal {Name = "T&F", JournalId = "THAM" }, new Journal {Name = "T&F", JournalId = "THER" },
                new Journal {Name = "T&F", JournalId = "THIE" }, new Journal {Name = "T&F", JournalId = "THPL" }, new Journal {Name = "T&F", JournalId = "TIBI" },
                new Journal {Name = "T&F", JournalId = "TICA" }, new Journal {Name = "T&F", JournalId = "TICE" }, new Journal {Name = "T&F", JournalId = "TIED" },
                new Journal {Name = "T&F", JournalId = "TIJO" }, new Journal {Name = "T&F", JournalId = "TITD" }, new Journal {Name = "T&F", JournalId = "TJAW" },
                new Journal {Name = "T&F", JournalId = "TJBD" }, new Journal {Name = "T&F", JournalId = "TJDE" }, new Journal {Name = "T&F", JournalId = "TJEM" },
                new Journal {Name = "T&F", JournalId = "TJHR" }, new Journal {Name = "T&F", JournalId = "TJID" }, new Journal {Name = "T&F", JournalId = "TJIM" },
                new Journal {Name = "T&F", JournalId = "TJMA" }, new Journal {Name = "T&F", JournalId = "TJOM" }, new Journal {Name = "T&F", JournalId = "TJOO" },
                new Journal {Name = "T&F", JournalId = "TJOS" }, new Journal {Name = "T&F", JournalId = "TJPI" }, new Journal {Name = "T&F", JournalId = "TJPS" },
                new Journal {Name = "T&F", JournalId = "TJPT" }, new Journal {Name = "T&F", JournalId = "TJRI" }, new Journal {Name = "T&F", JournalId = "TJSA" },
                new Journal {Name = "T&F", JournalId = "TLCR" }, new Journal {Name = "T&F", JournalId = "TLIM" }, new Journal {Name = "T&F", JournalId = "TMAM" },
                new Journal {Name = "T&F", JournalId = "TMAR" }, new Journal {Name = "T&F", JournalId = "TMIB" }, new Journal {Name = "T&F", JournalId = "TMMA" },
                new Journal {Name = "T&F", JournalId = "TMOS" }, new Journal {Name = "T&F", JournalId = "TMRL" }, new Journal {Name = "T&F", JournalId = "TNMP" },
                new Journal {Name = "T&F", JournalId = "TNZA" }, new Journal {Name = "T&F", JournalId = "TNZB" }, new Journal {Name = "T&F", JournalId = "TNZC" },
                new Journal {Name = "T&F", JournalId = "TNZE" }, new Journal {Name = "T&F", JournalId = "TNZG" }, new Journal {Name = "T&F", JournalId = "TNZK" },
                new Journal {Name = "T&F", JournalId = "TNZM" }, new Journal {Name = "T&F", JournalId = "TNZR" }, new Journal {Name = "T&F", JournalId = "TNZV" },
                new Journal {Name = "T&F", JournalId = "TNZZ" }, new Journal {Name = "T&F", JournalId = "TOSE" }, new Journal {Name = "T&F", JournalId = "TOST" },
                new Journal {Name = "T&F", JournalId = "TPOG" }, new Journal {Name = "T&F", JournalId = "TPSP" }, new Journal {Name = "T&F", JournalId = "TPSR" },
                new Journal {Name = "T&F", JournalId = "TQMA" }, new Journal {Name = "T&F", JournalId = "TRAM" }, new Journal {Name = "T&F", JournalId = "TRAN" },
                new Journal {Name = "T&F", JournalId = "TRBM" }, new Journal {Name = "T&F", JournalId = "TRMP" }, new Journal {Name = "T&F", JournalId = "TSED" },
                new Journal {Name = "T&F", JournalId = "TSFI" }, new Journal {Name = "T&F", JournalId = "TSFS" }, new Journal {Name = "T&F", JournalId = "TSIM" },
                new Journal {Name = "T&F", JournalId = "TSMS" }, new Journal {Name = "T&F", JournalId = "TSPM" }, new Journal {Name = "T&F", JournalId = "TSSC" },
                new Journal {Name = "T&F", JournalId = "TSSU" }, new Journal {Name = "T&F", JournalId = "TSTC" }, new Journal {Name = "T&F", JournalId = "TSUR" },
                new Journal {Name = "T&F", JournalId = "TTED" }, new Journal {Name = "T&F", JournalId = "TTPA" }, new Journal {Name = "T&F", JournalId = "TTRA" },
                new Journal {Name = "T&F", JournalId = "TTRB" }, new Journal {Name = "T&F", JournalId = "TTRS" }, new Journal {Name = "T&F", JournalId = "TTRV" },
                new Journal {Name = "T&F", JournalId = "TWST" }, new Journal {Name = "T&F", JournalId = "TZME" }, new Journal {Name = "T&F", JournalId = "WMHE" },
                new Journal {Name = "T&F", JournalId = "YAAC" }, new Journal {Name = "T&F", JournalId = "YAES" }, new Journal {Name = "T&F", JournalId = "YAMB" },
                new Journal {Name = "T&F", JournalId = "YATE" }, new Journal {Name = "T&F", JournalId = "YBAC" }, new Journal {Name = "T&F", JournalId = "YBAQ" },
                new Journal {Name = "T&F", JournalId = "YBLT" }, new Journal {Name = "T&F", JournalId = "YCAH" }, new Journal {Name = "T&F", JournalId = "YCAJ" },
                new Journal {Name = "T&F", JournalId = "YCAL" }, new Journal {Name = "T&F", JournalId = "YCBR" }, new Journal {Name = "T&F", JournalId = "YCCP" },
                new Journal {Name = "T&F", JournalId = "YCHI" }, new Journal {Name = "T&F", JournalId = "YCIH" }, new Journal {Name = "T&F", JournalId = "YCII" },
                new Journal {Name = "T&F", JournalId = "YCIP" }, new Journal {Name = "T&F", JournalId = "YCMQ" }, new Journal {Name = "T&F", JournalId = "YCOL" },
                new Journal {Name = "T&F", JournalId = "YCOU" }, new Journal {Name = "T&F", JournalId = "YCRH" }, new Journal {Name = "T&F", JournalId = "YCST" },
                new Journal {Name = "T&F", JournalId = "YDEI" }, new Journal {Name = "T&F", JournalId = "YDFI" }, new Journal {Name = "T&F", JournalId = "YDIX" },
                new Journal {Name = "T&F", JournalId = "YEJA" }, new Journal {Name = "T&F", JournalId = "YEMC" }, new Journal {Name = "T&F", JournalId = "YEMF" },
                new Journal {Name = "T&F", JournalId = "YENV" }, new Journal {Name = "T&F", JournalId = "YETH" }, new Journal {Name = "T&F", JournalId = "YHEM" },
                new Journal {Name = "T&F", JournalId = "YHSO" }, new Journal {Name = "T&F", JournalId = "YIAR" }, new Journal {Name = "T&F", JournalId = "YIDN" },
                new Journal {Name = "T&F", JournalId = "YIMM" }, new Journal {Name = "T&F", JournalId = "YIMR" }, new Journal {Name = "T&F", JournalId = "YIMS" },
                new Journal {Name = "T&F", JournalId = "YIRS" }, new Journal {Name = "T&F", JournalId = "YISR" }, new Journal {Name = "T&F", JournalId = "YITA" },
                new Journal {Name = "T&F", JournalId = "YJAC" }, new Journal {Name = "T&F", JournalId = "YJAF" }, new Journal {Name = "T&F", JournalId = "YJBR" },
                new Journal {Name = "T&F", JournalId = "YJCH" }, new Journal {Name = "T&F", JournalId = "YJCR" }, new Journal {Name = "T&F", JournalId = "YJFA" },
                new Journal {Name = "T&F", JournalId = "YJHM" }, new Journal {Name = "T&F", JournalId = "YJLI" }, new Journal {Name = "T&F", JournalId = "YJOR" },
                new Journal {Name = "T&F", JournalId = "YJPC" }, new Journal {Name = "T&F", JournalId = "YJPE" }, new Journal {Name = "T&F", JournalId = "YJRL" },
                new Journal {Name = "T&F", JournalId = "YJSS" }, new Journal {Name = "T&F", JournalId = "YJWA" }, new Journal {Name = "T&F", JournalId = "YKIV" },
                new Journal {Name = "T&F", JournalId = "YLAN" }, new Journal {Name = "T&F", JournalId = "YLDN" }, new Journal {Name = "T&F", JournalId = "YLEV" },
                new Journal {Name = "T&F", JournalId = "YLIT" }, new Journal {Name = "T&F", JournalId = "YLNQ" }, new Journal {Name = "T&F", JournalId = "YMCA" },
                new Journal {Name = "T&F", JournalId = "YMHJ" }, new Journal {Name = "T&F", JournalId = "YMMT" }, new Journal {Name = "T&F", JournalId = "YMNG" },
                new Journal {Name = "T&F", JournalId = "YMON" }, new Journal {Name = "T&F", JournalId = "YMPM" }, new Journal {Name = "T&F", JournalId = "YMSI" },
                new Journal {Name = "T&F", JournalId = "YMSS" }, new Journal {Name = "T&F", JournalId = "YMST" }, new Journal {Name = "T&F", JournalId = "YNAW" },
                new Journal {Name = "T&F", JournalId = "YNBI" }, new Journal {Name = "T&F", JournalId = "YNJB" }, new Journal {Name = "T&F", JournalId = "YNNS" },
                new Journal {Name = "T&F", JournalId = "YOGS" }, new Journal {Name = "T&F", JournalId = "YORG" }, new Journal {Name = "T&F", JournalId = "YOTB" },
                new Journal {Name = "T&F", JournalId = "YPAL" }, new Journal {Name = "T&F", JournalId = "YPAN" }, new Journal {Name = "T&F", JournalId = "YPAT" },
                new Journal {Name = "T&F", JournalId = "YPEQ" }, new Journal {Name = "T&F", JournalId = "YPOM" }, new Journal {Name = "T&F", JournalId = "YPOT" },
                new Journal {Name = "T&F", JournalId = "YPPC" }, new Journal {Name = "T&F", JournalId = "YPRC" }, new Journal {Name = "T&F", JournalId = "YPRT" },
                new Journal {Name = "T&F", JournalId = "YPUA" }, new Journal {Name = "T&F", JournalId = "YREF" }, new Journal {Name = "T&F", JournalId = "YRER" },
                new Journal {Name = "T&F", JournalId = "YRRR" }, new Journal {Name = "T&F", JournalId = "YRUR" }, new Journal {Name = "T&F", JournalId = "YSCM" },
                new Journal {Name = "T&F", JournalId = "YSDH" }, new Journal {Name = "T&F", JournalId = "YSEA" }, new Journal {Name = "T&F", JournalId = "YSIC" },
                new Journal {Name = "T&F", JournalId = "YSLA" }, new Journal {Name = "T&F", JournalId = "YSLH" }, new Journal {Name = "T&F", JournalId = "YSRE" },
                new Journal {Name = "T&F", JournalId = "YSSA" }, new Journal {Name = "T&F", JournalId = "YSTA" }, new Journal {Name = "T&F", JournalId = "YSTR" },
                new Journal {Name = "T&F", JournalId = "YSTW" }, new Journal {Name = "T&F", JournalId = "YSUE" }, new Journal {Name = "T&F", JournalId = "YTAV" },
                new Journal {Name = "T&F", JournalId = "YTCC" }, new Journal {Name = "T&F", JournalId = "YTCR" }, new Journal {Name = "T&F", JournalId = "YTHS" },
                new Journal {Name = "T&F", JournalId = "YTIM" }, new Journal {Name = "T&F", JournalId = "YTNG" }, new Journal {Name = "T&F", JournalId = "YWAC" },
                new Journal {Name = "T&F", JournalId = "YWPJ" },

                new Journal {Name = "OUP", JournalId = "AMJHSP" }, new Journal {Name = "OUP", JournalId = "ASJOFJ" }, new Journal {Name = "OUP", JournalId = "ASJOUR" },
                new Journal {Name = "OUP", JournalId = "BJDERM" }, new Journal {Name = "OUP", JournalId = "BJSOPE" }, new Journal {Name = "OUP", JournalId = "BJSURG" },
                new Journal {Name = "OUP", JournalId = "BRAINJ" }, new Journal {Name = "OUP", JournalId = "BRCOMS" }, new Journal {Name = "OUP", JournalId = "CEDERM" },
                new Journal {Name = "OUP", JournalId = "CLCHEM" }, new Journal {Name = "OUP", JournalId = "CLINID" }, new Journal {Name = "OUP", JournalId = "CVRESE" },
                new Journal {Name = "OUP", JournalId = "EHEART" }, new Journal {Name = "OUP", JournalId = "EHJACC" }, new Journal {Name = "OUP", JournalId = "EHJCRE" },
                new Journal {Name = "OUP", JournalId = "EHJDHE" }, new Journal {Name = "OUP", JournalId = "EHJIMP" }, new Journal {Name = "OUP", JournalId = "EHJOPN" },
                new Journal {Name = "OUP", JournalId = "EJECHO" }, new Journal {Name = "OUP", JournalId = "EJENDO" }, new Journal {Name = "OUP", JournalId = "ENDOCR" },
                new Journal {Name = "OUP", JournalId = "ENDREV" }, new Journal {Name = "OUP", JournalId = "EUPACE" }, new Journal {Name = "OUP", JournalId = "EURJCN" },
                new Journal {Name = "OUP", JournalId = "EURJPC" }, new Journal {Name = "OUP", JournalId = "GBEVOL" }, new Journal {Name = "OUP", JournalId = "GENETS" },
                new Journal {Name = "OUP", JournalId = "GTHREE" }, new Journal {Name = "OUP", JournalId = "HASCHL" }, new Journal {Name = "OUP", JournalId = "INFDIS" },
                new Journal {Name = "OUP", JournalId = "JACAMR" }, new Journal {Name = "OUP", JournalId = "JALMED" }, new Journal {Name = "OUP", JournalId = "JCEMCR" },
                new Journal {Name = "OUP", JournalId = "JCEMET" }, new Journal {Name = "OUP", JournalId = "JESOCI" }, new Journal {Name = "OUP", JournalId = "JLEUKO" },
                new Journal {Name = "OUP", JournalId = "JOPEDU" }, new Journal {Name = "OUP", JournalId = "JRSSIG" }, new Journal {Name = "OUP", JournalId = "JRSSSA" },
                new Journal {Name = "OUP", JournalId = "JRSSSB" }, new Journal {Name = "OUP", JournalId = "JRSSSC" }, new Journal {Name = "OUP", JournalId = "MICMIC" },
                new Journal {Name = "OUP", JournalId = "MOLBEV" }, new Journal {Name = "OUP", JournalId = "OFIDIS" }, new Journal {Name = "OUP", JournalId = "PLCELL" },
                new Journal {Name = "OUP", JournalId = "PLPYHS" }, new Journal {Name = "OUP", JournalId = "PNEXUS" }, new Journal {Name = "OUP", JournalId = "PSQUAR" },
                new Journal {Name = "OUP", JournalId = "RESTUD" }, new Journal {Name = "OUP", JournalId = "SEHEART" },

                new Journal {Name = "Sage", JournalId = "ACD" }, new Journal {Name = "Sage", JournalId = "ACT" }, new Journal {Name = "Sage", JournalId = "AJR" },
                new Journal {Name = "Sage", JournalId = "ANJ" }, new Journal {Name = "Sage", JournalId = "ANT" }, new Journal {Name = "Sage", JournalId = "CEJ" },
                new Journal {Name = "Sage", JournalId = "CET" }, new Journal {Name = "Sage", JournalId = "EEG" }, new Journal {Name = "Sage", JournalId = "EHQ" },
                new Journal {Name = "Sage", JournalId = "ELJ" }, new Journal {Name = "Sage", JournalId = "EPE" }, new Journal {Name = "Sage", JournalId = "EPJ" },
                new Journal {Name = "Sage", JournalId = "EPN" }, new Journal {Name = "Sage", JournalId = "ETS" }, new Journal {Name = "Sage", JournalId = "EUP" },
                new Journal {Name = "Sage", JournalId = "HHS" }, new Journal {Name = "Sage", JournalId = "IJLEW" }, new Journal {Name = "Sage", JournalId = "IJPP" },
                new Journal {Name = "Sage", JournalId = "IJSP" }, new Journal {Name = "Sage", JournalId = "IRJ" }, new Journal {Name = "Sage", JournalId = "IRS" },
                new Journal {Name = "Sage", JournalId = "JABS" }, new Journal {Name = "Sage", JournalId = "JBTC" }, new Journal {Name = "Sage", JournalId = "JHN" },
                new Journal {Name = "Sage", JournalId = "JLOS" }, new Journal {Name = "Sage", JournalId = "JMB" }, new Journal {Name = "Sage", JournalId = "JMM(K)" },
                new Journal {Name = "Sage", JournalId = "JOH" }, new Journal {Name = "Sage", JournalId = "JOPON" }, new Journal {Name = "Sage", JournalId = "JOSN" },
                new Journal {Name = "Sage", JournalId = "JRE" }, new Journal {Name = "Sage", JournalId = "JSC" }, new Journal {Name = "Sage", JournalId = "JSE" },
                new Journal {Name = "Sage", JournalId = "JSW" }, new Journal {Name = "Sage", JournalId = "JTH" }, new Journal {Name = "Sage", JournalId = "JTT" },
                new Journal {Name = "Sage", JournalId = "JTW" }, new Journal {Name = "Sage", JournalId = "MIE" }, new Journal {Name = "Sage", JournalId = "MSL" },
                new Journal {Name = "Sage", JournalId = "NAA" }, new Journal {Name = "Sage", JournalId = "NQH" }, new Journal {Name = "Sage", JournalId = "ORM" },
                new Journal {Name = "Sage", JournalId = "OTR" },new Journal {Name = "Sage", JournalId = "PIE" }, new Journal {Name = "Sage", JournalId = "PIJ" },
                new Journal {Name = "Sage", JournalId = "PLJ" }, new Journal {Name = "Sage", JournalId = "PSM" }, new Journal {Name = "Sage", JournalId = "RAJ" },
                new Journal {Name = "Sage", JournalId = "RAS" }, new Journal {Name = "Sage", JournalId = "RBP" }, new Journal {Name = "Sage", JournalId = "ROE" },
                new Journal {Name = "Sage", JournalId = "SHR" }, new Journal {Name = "Sage", JournalId = "TFJ" }, new Journal {Name = "Sage", JournalId = "TIA" },
                new Journal {Name = "Sage", JournalId = "TTJ" }, new Journal {Name = "Sage", JournalId = "UAR" }, new Journal {Name = "Sage", JournalId = "VAW" },
                new Journal {Name = "Sage", JournalId = "WAF" },

                new Journal {Name = "CUP", JournalId = "AAP" }, new Journal {Name = "CUP", JournalId = "AAQ" }, new Journal {Name = "CUP", JournalId = "ACL" },
                new Journal {Name = "CUP", JournalId = "AFB" }, new Journal {Name = "CUP", JournalId = "AFH" }, new Journal {Name = "CUP", JournalId = "AFR" },
                new Journal {Name = "CUP", JournalId = "AGE" }, new Journal {Name = "CUP", JournalId = "AGS" }, new Journal {Name = "CUP", JournalId = "AHR" },
                new Journal {Name = "CUP", JournalId = "AHY" }, new Journal {Name = "CUP", JournalId = "AIE" }, new Journal {Name = "CUP", JournalId = "AJI" },
                new Journal {Name = "CUP", JournalId = "AJL" }, new Journal {Name = "CUP", JournalId = "AJS" }, new Journal {Name = "CUP", JournalId = "AJU" },
                new Journal {Name = "CUP", JournalId = "ALJ" }, new Journal {Name = "CUP", JournalId = "ALS" }, new Journal {Name = "CUP", JournalId = "AMP" },
                new Journal {Name = "CUP", JournalId = "AMS" }, new Journal {Name = "CUP", JournalId = "ANN" }, new Journal {Name = "CUP", JournalId = "ANS" },
                new Journal {Name = "CUP", JournalId = "AOG" }, new Journal {Name = "CUP", JournalId = "APA" }, new Journal {Name = "CUP", JournalId = "APL" },
                new Journal {Name = "CUP", JournalId = "AQY" }, new Journal {Name = "CUP", JournalId = "ARH" }, new Journal {Name = "CUP", JournalId = "ASI" },
                new Journal {Name = "CUP", JournalId = "ASO" }, new Journal {Name = "CUP", JournalId = "ASP" }, new Journal {Name = "CUP", JournalId = "ASS" },
                new Journal {Name = "CUP", JournalId = "ATH" }, new Journal {Name = "CUP", JournalId = "ATM" }, new Journal {Name = "CUP", JournalId = "BAP" },
                new Journal {Name = "CUP", JournalId = "BBS" }, new Journal {Name = "CUP", JournalId = "BEC" }, new Journal {Name = "CUP", JournalId = "BER" },
                new Journal {Name = "CUP", JournalId = "BHR" }, new Journal {Name = "CUP", JournalId = "BIL" }, new Journal {Name = "CUP", JournalId = "BJA" },
                new Journal {Name = "CUP", JournalId = "BJB" }, new Journal {Name = "CUP", JournalId = "BJH" }, new Journal {Name = "CUP", JournalId = "BJI" },
                new Journal {Name = "CUP", JournalId = "BJO" }, new Journal {Name = "CUP", JournalId = "BJP" }, new Journal {Name = "CUP", JournalId = "BJT" },
                new Journal {Name = "CUP", JournalId = "BPP" }, new Journal {Name = "CUP", JournalId = "BRI" }, new Journal {Name = "CUP", JournalId = "BSO" },
                new Journal {Name = "CUP", JournalId = "BYZ" }, new Journal {Name = "CUP", JournalId = "CAJ" }, new Journal {Name = "CUP", JournalId = "CAQ" },
                new Journal {Name = "CUP", JournalId = "CAR" }, new Journal {Name = "CUP", JournalId = "CCC" }, new Journal {Name = "CUP", JournalId = "CCJ" },
                new Journal {Name = "CUP", JournalId = "CEH" }, new Journal {Name = "CUP", JournalId = "CEL" }, new Journal {Name = "CUP", JournalId = "CEM" },
                new Journal {Name = "CUP", JournalId = "CHH" }, new Journal {Name = "CUP", JournalId = "CJP" }, new Journal {Name = "CUP", JournalId = "CLJ" },
                new Journal {Name = "CUP", JournalId = "CLM" }, new Journal {Name = "CUP", JournalId = "CNJ" }, new Journal {Name = "CUP", JournalId = "CNN/CONCUP" },
                new Journal {Name = "CUP", JournalId = "COR" }, new Journal {Name = "CUP", JournalId = "CQY" }, new Journal {Name = "CUP", JournalId = "CSS" },
                new Journal {Name = "CUP", JournalId = "DAR" }, new Journal {Name = "CUP", JournalId = "DEM" }, new Journal {Name = "CUP", JournalId = "DPP" },
                new Journal {Name = "CUP", JournalId = "DRJ" }, new Journal {Name = "CUP", JournalId = "EAA" }, new Journal {Name = "CUP", JournalId = "EAC" },
                new Journal {Name = "CUP", JournalId = "ECH" }, new Journal {Name = "CUP", JournalId = "ECM" }, new Journal {Name = "CUP", JournalId = "EDE" },
                new Journal {Name = "CUP", JournalId = "EHS" }, new Journal {Name = "CUP", JournalId = "EIA" }, new Journal {Name = "CUP", JournalId = "EIS" },
                new Journal {Name = "CUP", JournalId = "ELJ" }, new Journal {Name = "CUP", JournalId = "ELL" }, new Journal {Name = "CUP", JournalId = "ENG" },
                new Journal {Name = "CUP", JournalId = "EPI" }, new Journal {Name = "CUP", JournalId = "EPS" }, new Journal {Name = "CUP", JournalId = "ERM" },
                new Journal {Name = "CUP", JournalId = "FHR" }, new Journal {Name = "CUP", JournalId = "GAR" }, new Journal {Name = "CUP", JournalId = "GHG" },
                new Journal {Name = "CUP", JournalId = "GMH" }, new Journal {Name = "CUP", JournalId = "GOV" }, new Journal {Name = "CUP", JournalId = "GRH" },
                new Journal {Name = "CUP", JournalId = "HEP" }, new Journal {Name = "CUP", JournalId = "HEQ" }, new Journal {Name = "CUP", JournalId = "HGL" },
                new Journal {Name = "CUP", JournalId = "HIS" }, new Journal {Name = "CUP", JournalId = "HOR" }, new Journal {Name = "CUP", JournalId = "HYG" },
                new Journal {Name = "CUP", JournalId = "IHS" }, new Journal {Name = "CUP", JournalId = "IJA" }, new Journal {Name = "CUP", JournalId = "IJC" },
                new Journal {Name = "CUP", JournalId = "ILM" }, new Journal {Name = "CUP", JournalId = "ILQ" }, new Journal {Name = "CUP", JournalId = "ILW" },
                new Journal {Name = "CUP", JournalId = "INO" }, new Journal {Name = "CUP", JournalId = "INT" }, new Journal {Name = "CUP", JournalId = "IPO" },
                new Journal {Name = "CUP", JournalId = "IRC" }, new Journal {Name = "CUP", JournalId = "IRQ" }, new Journal {Name = "CUP", JournalId = "ISH" },
                new Journal {Name = "CUP", JournalId = "ISR" }, new Journal {Name = "CUP", JournalId = "ITI" }, new Journal {Name = "CUP", JournalId = "JAL" },
                new Journal {Name = "CUP", JournalId = "JAN" }, new Journal {Name = "CUP", JournalId = "JAS" }, new Journal {Name = "CUP", JournalId = "JBR" },
                new Journal {Name = "CUP", JournalId = "JCH" }, new Journal {Name = "CUP", JournalId = "JCL" }, new Journal {Name = "CUP", JournalId = "JCT" },
                new Journal {Name = "CUP", JournalId = "JEA" }, new Journal {Name = "CUP", JournalId = "JGA" }, new Journal {Name = "CUP", JournalId = "JHL" },
                new Journal {Name = "CUP", JournalId = "JIE" }, new Journal {Name = "CUP", JournalId = "JJP" }, new Journal {Name = "CUP", JournalId = "JLI" },
                new Journal {Name = "CUP", JournalId = "JLO" }, new Journal {Name = "CUP", JournalId = "JLR" }, new Journal {Name = "CUP", JournalId = "JMO" },
                new Journal {Name = "CUP", JournalId = "JNS" }, new Journal {Name = "CUP", JournalId = "JOG" }, new Journal {Name = "CUP", JournalId = "JOI" },
                new Journal {Name = "CUP", JournalId = "JPA" }, new Journal {Name = "CUP", JournalId = "JPS" }, new Journal {Name = "CUP", JournalId = "JRA" },
                new Journal {Name = "CUP", JournalId = "JRR" }, new Journal {Name = "CUP", JournalId = "JRS" }, new Journal {Name = "CUP", JournalId = "JSC" },
                new Journal {Name = "CUP", JournalId = "JWE" }, new Journal {Name = "CUP", JournalId = "LAQ" }, new Journal {Name = "CUP", JournalId = "LAS" },
                new Journal {Name = "CUP", JournalId = "LEG" }, new Journal {Name = "CUP", JournalId = "LHR" }, new Journal {Name = "CUP", JournalId = "LIC" },
                new Journal {Name = "CUP", JournalId = "LIM" }, new Journal {Name = "CUP", JournalId = "LIS" }, new Journal {Name = "CUP", JournalId = "LPB" },
                new Journal {Name = "CUP", JournalId = "LST" }, new Journal {Name = "CUP", JournalId = "LSY" }, new Journal {Name = "CUP", JournalId = "LTA" },
                new Journal {Name = "CUP", JournalId = "LVC" }, new Journal {Name = "CUP", JournalId = "MAH" }, new Journal {Name = "CUP", JournalId = "MAM" },
                new Journal {Name = "CUP", JournalId = "MBI" }, new Journal {Name = "CUP", JournalId = "MES" }, new Journal {Name = "CUP", JournalId = "MGM" },
                new Journal {Name = "CUP", JournalId = "MIH" }, new Journal {Name = "CUP", JournalId = "MIT" }, new Journal {Name = "CUP", JournalId = "MOA" },
                new Journal {Name = "CUP", JournalId = "MOR" }, new Journal {Name = "CUP", JournalId = "MRC" }, new Journal {Name = "CUP", JournalId = "MRF" },
                new Journal {Name = "CUP", JournalId = "MTO" }, new Journal {Name = "CUP", JournalId = "NAV" }, new Journal {Name = "CUP", JournalId = "NCM" },
                new Journal {Name = "CUP", JournalId = "NSY" }, new Journal {Name = "CUP", JournalId = "NTS" }, new Journal {Name = "CUP", JournalId = "NUTSOC" },
                new Journal {Name = "CUP", JournalId = "OPR" }, new Journal {Name = "CUP", JournalId = "ORX" }, new Journal {Name = "CUP", JournalId = "PAB" },
                new Journal {Name = "CUP", JournalId = "PAG" }, new Journal {Name = "CUP", JournalId = "PAO" }, new Journal {Name = "CUP", JournalId = "PAR" },
                new Journal {Name = "CUP", JournalId = "PAX" }, new Journal {Name = "CUP", JournalId = "PDJ" }, new Journal {Name = "CUP", JournalId = "PEF" },
                new Journal {Name = "CUP", JournalId = "PEM" }, new Journal {Name = "CUP", JournalId = "PES" }, new Journal {Name = "CUP", JournalId = "PGR" },
                new Journal {Name = "CUP", JournalId = "PHI" }, new Journal {Name = "CUP", JournalId = "PHO" }, new Journal {Name = "CUP", JournalId = "PHS" },
                new Journal {Name = "CUP", JournalId = "PMM" }, new Journal {Name = "CUP", JournalId = "PMU" }, new Journal {Name = "CUP", JournalId = "PNS" },
                new Journal {Name = "CUP", JournalId = "PRM" }, new Journal {Name = "CUP", JournalId = "PSM" }, new Journal {Name = "CUP", JournalId = "QRB" },
                new Journal {Name = "CUP", JournalId = "QUA" }, new Journal {Name = "CUP", JournalId = "RAC" }, new Journal {Name = "CUP", JournalId = "RAF" },
                new Journal {Name = "CUP", JournalId = "RAM" }, new Journal {Name = "CUP", JournalId = "RAP" }, new Journal {Name = "CUP", JournalId = "REP" },
                new Journal {Name = "CUP", JournalId = "RES" }, new Journal {Name = "CUP", JournalId = "RHC" }, new Journal {Name = "CUP", JournalId = "RHE" },
                new Journal {Name = "CUP", JournalId = "RHT" }, new Journal {Name = "CUP", JournalId = "RIS" }, new Journal {Name = "CUP", JournalId = "RMS" },
                new Journal {Name = "CUP", JournalId = "RMU" }, new Journal {Name = "CUP", JournalId = "ROM" }, new Journal {Name = "CUP", JournalId = "ROP" },
                new Journal {Name = "CUP", JournalId = "RQX" }, new Journal {Name = "CUP", JournalId = "SAM" }, new Journal {Name = "CUP", JournalId = "SAP" },
                new Journal {Name = "CUP", JournalId = "SEA" }, new Journal {Name = "CUP", JournalId = "SIP" }, new Journal {Name = "CUP", JournalId = "SJT" },
                new Journal {Name = "CUP", JournalId = "SLR" }, new Journal {Name = "CUP", JournalId = "SSR" }, new Journal {Name = "CUP", JournalId = "STC" },
                new Journal {Name = "CUP", JournalId = "SUS" }, new Journal {Name = "CUP", JournalId = "TAM" }, new Journal {Name = "CUP", JournalId = "TCM" },
                new Journal {Name = "CUP", JournalId = "TDO" }, new Journal {Name = "CUP", JournalId = "TEL" }, new Journal {Name = "CUP", JournalId = "TEM" },
                new Journal {Name = "CUP", JournalId = "THC" }, new Journal {Name = "CUP", JournalId = "THI" }, new Journal {Name = "CUP", JournalId = "TRE" },
                new Journal {Name = "CUP", JournalId = "TRI" }, new Journal {Name = "CUP", JournalId = "TRN" }, new Journal {Name = "CUP", JournalId = "TSY" },
                new Journal {Name = "CUP", JournalId = "UHY" }, new Journal {Name = "CUP", JournalId = "UTI" }, new Journal {Name = "CUP", JournalId = "VLC" },
                new Journal {Name = "CUP", JournalId = "WPT" }, new Journal {Name = "CUP", JournalId = "WTR" },

                new Journal {Name = "ASCE", JournalId = "AE" }, new Journal {Name = "ASCE", JournalId = "BE" }, new Journal {Name = "ASCE", JournalId = "CC" },
                new Journal {Name = "ASCE", JournalId = "CR" }, new Journal {Name = "ASCE", JournalId = "GM" }, new Journal {Name = "ASCE", JournalId = "HZ" },
                new Journal {Name = "ASCE", JournalId = "UP" }, new Journal {Name = "ASCE", JournalId = "WW" },

                new Journal {Name = "ASME", JournalId = "JAM" }, new Journal {Name = "ASME", JournalId = "JCISE" }, new Journal {Name = "ASME", JournalId = "JEECS" },
                new Journal {Name = "ASME", JournalId = "JERT" }, new Journal {Name = "ASME", JournalId = "JESBC" }, new Journal {Name = "ASME", JournalId = "JESBC" },
                new Journal {Name = "ASME", JournalId = "JMR" }, new Journal {Name = "ASME", JournalId = "MANU" }, new Journal {Name = "ASME", JournalId = "MATS" },
                new Journal {Name = "ASME", JournalId = "MD" }, new Journal {Name = "ASME", JournalId = "NDE" }, new Journal {Name = "ASME", JournalId = "OMAE" },
                new Journal {Name = "ASME", JournalId = "SOL" }, new Journal {Name = "ASME", JournalId = "TRIB" }, new Journal {Name = "ASME", JournalId = "TSEA" },
                new Journal {Name = "ASME", JournalId = "TURBO" }, new Journal {Name = "ASME", JournalId = "VIB" },

                new Journal {Name = "Optica", JournalId = "" },

                new Journal {Name = "SfN", JournalId = "JNeurosci" }, new Journal {Name = "SfN", JournalId = "eNeuro" },

                new Journal {Name = "NCTM", JournalId = "JRME" }, new Journal {Name = "NCTM", JournalId = "MTE" }, new Journal {Name = "NCTM", JournalId = "MTLT" },

                new Journal {Name = "APA", JournalId = "" },

                new Journal {Name = "Others", JournalId = "" }
            };
        }

        public List<Journal> GetJournalIdByPublisherName(string publisherName)
        {
            return _journalName.Where(x => x.Name == publisherName).ToList();
        }
    }
}









