using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NTDataHiveEnum.DataPlugins.Enums
{
    public enum ErrorLocation
    {
        Abbreviations,
        Abstract,
        Acknowledgement,
        Affiliations,
        Appendix_Section,
        Article_Note,
        Article_Title,
        Author_Contributions,
        Author_Group,
        Author_Note,
        Banner,
        Biography,
        BM_Order,
        Body_Text,
        Citations,
        COI,
        Collab_Author,
        Collaboration_Section,
        Commercial_Affiliations,
        Copyright,
        Corr_Field,
        DAS,
        Disclosure,
        Displayed_Quote,
        Doc_Type,
        Ed_Rev_Details,
        Equal_Contribution,
        Equations,
        Ethics_Statement,
        Figures,
        Funding,
        Glossary,
        Graph_Abstract,
        History_Dates,
        Introduction,
        Keywords,
        List,
        LRH,
        Markups,
        ORCID,
        Pagination,
        Present_Address,
        Query,
        References,
        Related_Article_Blurb,
        RRH,
        Section_Heading,
        Specialty_Section,
        Supplementary_Material,
        Tables,
        Textbox,
        URL,
        Others,
    }
}
